/* Formatted on 12/6/2022 3:43:52 PM (QP5 v5.227.12220.39754) */
ALTER TABLE RAW04.PRODUCT_GROUP ADD (USER1 VARCHAR2(50));
ALTER TABLE RAW04.GOODS_REC_M ADD (USER1 VARCHAR2(50));

ALTER TABLE PROD_INFO ADD (DIST VARCHAR2(100),
                           THREE_P VARCHAR2(100)
);
/

ALTER TABLE PROD_INFO ADD (DIST_ID VARCHAR2(100));

ALTER TABLE  raw04.GOODS_REC_M ADD(REBATE_MONTH DATE);


ALTER TABLE GOODS_DISTRIBUTION_M ADD (user1 VARCHAR2(50));


ALTER TABLE GOODS_DISPATCH_M ADD (user1 VARCHAR2(50));


ALTER TABLE GOODS_DISPATCH_M ADD (CAR_NO VARCHAR2(200));


ALTER TABLE TRANSFER_RECEIVE_M ADD (USER1 VARCHAR2(50));

ALTER TABLE TAX_CERTIFICATE_M ADD (USER1 VARCHAR2(50));

ALTER TABLE TAX_CERTIFICATE_M ADD (COMP_NAME VARCHAR2(200));

ALTER TABLE TAX_CERTIFICATE_M ADD (COMP_ID number(20));

ALTER TABLE hscode_info ADD (YEAR VARCHAR2(20));

