/* Formatted on 1/1/2023 11:48:38 AM (QP5 v5.227.12220.39754) */
CREATE TABLE M_MEMBER
(
   ID           NUMBER,
   FULL_NAME    VARCHAR2 (100),
   PHONE        VARCHAR2 (30),
   EMAIL        VARCHAR2 (30),
   PICTURE      BLOB,
   ADDRESS      VARCHAR2 (200),
   NID          VARCHAR2 (20),
   PROFESSION   VARCHAR2 (50),
   PRIMARY KEY (ID) USING INDEX ENABLE
)
/

CREATE TABLE MEAL_PERIOD
(
   ID          NUMBER,
   MEAL_ID     NUMBER,
   BREAKFAST   NUMBER (1, 0),
   LUNCH       NUMBER (1, 0),
   DINNER      NUMBER (1, 0),
   PRIMARY KEY (ID) USING INDEX ENABLE
)
/

CREATE TABLE SHOP_EXP
(
   ID           NUMBER,
   SHOP_DATE    DATE,
   SHOPPER_ID   NUMBER,
   COST_AMT     NUMBER (10, 2),
   OTHER_COST   NUMBER (10, 2),
   PRIMARY KEY (ID) USING INDEX ENABLE
)
/

CREATE TABLE CASH_SUB
(
   ID            NUMBER,
   M_MEMBER_ID   NUMBER,
   CASH_AMT      NUMBER (10, 2),
   CASH_SUB      DATE,
   PRIMARY KEY (ID) USING INDEX ENABLE
)
/

CREATE TABLE MEAL_COUNT
(
   ID          NUMBER (20, 0),
   M_ID        NUMBER,
   MEAL_DATE   DATE,
   PRIMARY KEY (ID) USING INDEX ENABLE
)
/