GRANT SELECT ON SYS.USER$ TO RAW04;
GRANT DBA TO RAW04;
ALTER USER RAW04 DEFAULT ROLE ALL;
GRANT UNLIMITED TABLESPACE TO RAW04;
GRANT EXECUTE ON SYS.DBMS_CRYPTO TO RAW04;
GRANT SELECT ON SYS.USER$ TO RAW04;
GRANT SELECT ON SYS.V_$MYSTAT TO RAW04;
GRANT SELECT ON SYS.V_$SESSION TO RAW04;
ALTER USER RAW04  GRANT CONNECT THROUGH ORDS_PUBLIC_USER;
/
